id: I56D4B3A1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:05:47+00:00'
last_modified: '2022-06-08T04:46:27.542729+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20658
  title: མན་ངག་རིན་ཆེན་འཕྲེང་བ་བྲང་ཏིའི་ལྷ་རྗེའི་ཁྱད་ཆོས་གསེར་བྲེ་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    050B:
      image_group_id: I8LS20660
      title: ''
      total_pages: 554
      order: 1
      base_file: 050B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
