id: P005539
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:58:16.015125
source_metadata:
  id: bdr:W8LS20658
  title: མན་ངག་རིན་ཆེན་འཕྲེང་བ་བྲང་ཏིའི་ལྷ་རྗེའི་ཁྱད་ཆོས་གསེར་བྲེ་མ།
  author: ''
  volumes:
    6a93aa898b444961b4c57d662d6cd1bc:
      image_group_id: I8LS20660
      title: ''
      volume_number: 1
      total_pages: 554
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
